[package]
name = "wasmrain"
version = "0.1.0"
authors = ["Matěj Laitl <matej@laitl.cz>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_log = "0.2.0"
log = "0.4.11"
wasm-bindgen = "0.2.68"
web-sys = { version = "0.3.45", features = ["Window"] }
